name: senior_design
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.31.1
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.7.6
  firebase_database: 10.5.6
  image_picker: ^1.1.1
  cupertino_icons: ^1.0.6
  lottie: ^3.1.2
  google_sign_in: ^5.4.1
  flutter_signin_button: ^2.0.0
  sign_in_with_apple: ^4.0.0
  intl: ^0.17.0
  google_maps_flutter: ^2.6.1
  location: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/
    - lib/animations/
    - assets/
